// DINAMIKUS MEMORIAKEZELES

// PROBLEMA - NEM TUDJUK ELORE, HOGY MENNYI MEMORIARA LESZ SZUKSEGUNK
// + NEM TUDJUK KONTROLLALNI AZ ELETTARTAMOT
// ELETTARTAM PROBLEMA : GLOB.VALTOZO AKKOR IS LETEZIK, AMIKOR EPPEN NINCS RA SZUKSEG -> FELESLEGESEN FOGLALJA A MEMORIAT
// A HATALMAS TOMB NEM FER BE A VEREMBE - ELHASZNALJUK A FUGGVENYHIVASOK KIVITELEZESEHEZ SZUKSEGES MEMORIAT
// 
// CELOK : 1. ELDONTHETUK, HOGY MENNYI MEMORIAT FOGLALUNK
//         2. MIKOR FOGLALUNK MEMORIAT, ES MIKOR SZABADITJUK FEL
// CSEREBE : SAJAT FELELOSSEGUNK A FOGLALAS ES A FELSZABADITAS IS
// HA ELFELEJTJUK MEGTENNI - PROGRAMUNK FOLYTON NOVEKSZIK, ES LE FOG ALLNI
 
// malloc() ES A free() FGV
// A FGV PAROS BIZTOSITJA A C NYELV DINAMIKUS MEMORIAKEZELESET

// void* malloc(size_t meret)
// MALLOC = MEMORY ALLOCATION
// LEFOGLAL LEGALABB 1 BAJTBAN MEGADOTT MERETU MEMORIATERULETET
// VISSZAAD EGY CIMET A LEFOGLALT MEMORIA T-RE
// A MEMORIA MERETE meret BAJJT, ES INICIALIZALATLAN (MEMORIASZEMET)
// HA NEM SIKERULT, AKKOR NULL POINTERT AD BISSZA

// void* free (void* ptr)
// FELSZABADIT EGY MEMORIATERULETET, AMIT A malloc() FOGLALT
// A malloc() ALTAL ADOTT CIMET KELL NEKI ADNI

// PL.: MÉRET FOGLALÁSA 

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define Error 1
#define NoError 0

char* osszefuz (char const* s1, char const* s2);

int main (void) {
    int n;
    printf("Hany szamot?");
    scanf("%d", &n);
    // TOMB 0. ELEMERE MUTATO POINTER LETREHOZASA
    double* tomb;
    // MEMORIA FOGLALASA
    tomb = (double*) malloc(n * sizeof(double));
    // MEMORIA FOGLALASANAK ELLENORZESE
    if (tomb == NULL) {
        printf("Nem sikerult memoriat foglalni!\n");
        return Error;
    }
    // TOMB 4. ELEMENEK ERTEK ADASA POINTER SEGITSEGEVEL
    tomb [3] = 12;
    // MEMORIA FELSZABADITASA
    free(tomb);

    char const* s1 = "Hegyesi ";
    char const* s2 = "Akos";

    char* str;
    // POINTER ERTEKADAS
    str = osszefuz(s1, s2);
    // OSSZEFUZOTT STRING KIIRATASA
    printf("%s", str);
    printf("\n");
    // 
    free(str);

    return NoError;
}

// A LEFOGLALT TERULETRE EGY *void MUTATOT KAPUNK, MERT A malloc() NEM TUDJA, HOGY MILYEN TIPUSUAK A LEFOGLALT MEMORIAK
// EZT A VOID TIPUST ALAKITJUK A SAJAT TIPUSUNKRA MUTATO POINTERRE (dobule*) IGY TAROLJUK EL A POINTERUNKBEN
// MALLOC NEM TUD SEMMIT A FOGLALT TERULETROL
// NEKUNK KELL KISZAMITANI A MERETET BAJTOKBAN (SZORZASSAL)
// sizeof OPERATORRAL TUDJUK KISZAMITANI + A SZUKSEGES TIPUSSAL, EZT SZOROZZUK AZ ELEMSZAMMAL
// POINTEREN KERESZTUL ERJUK EL A MEMORIATERULETET
// FREE UTÁN NEM SZABAD HIVATKOZNI AZ ADOTT MEMORIA CIMRE
// ERDEMES A POINTERJET NULL-RA ALLITANI
// C99 OTA EKVIVALENS EZZEL : scanf("%d", &n); double tomb [n];

// PL.: ÉLETTARTAM
// OSSZAFUZ 2 PARAMETERKENT KAPOTT STRINGET + VISSZATERESI ERTEK = OSSZEFUZOTT STRING
// VISSZATERESI ERTEKET EL KELL MENTENI EGY VALTOZOBAN, HISZEN HIVAS UTAN ELFELEJTI

char* osszefuz (char const* s1, char const* s2) {
    int mennyi = strlen(s1) + strlen (s2) + 1;
    // MEMORIA FOGLALASA
    char* res = (char*) malloc (mennyi * sizeof(char));
    if (res == NULL) {
        return NULL;
    }
    // S1 STRING BEMASOLASA RES-BE
    strcpy(res, s1);
    // S2 STRING HOZZAFUZESE RES-HEZ
    strcat(res, s2);

    return res;
}

// HA A HIVO DOLGA A FELSZABADITAS, AKKOR AZT DOKUMENTALNI KELL
// HA A VALTOZO ELETTARTAMA ATIVEL EGY FUGGVENYEN, BIZZUK RA VALAKIRE

// FONTOS BETARTANDO SZABALYOK!!
// LEFOGLALT MEMORIA TERULETET FEL KELL SZABADITANI - AHANY MALLOC (), ANNYI FREE () !!
// MALLOC ALTAL ADOTT POINTER NAGYON FONTOS, HA ELVESZITJUK, NEM TUDJUK MAJD VISSZAADNI !!
// ALLOKALATLAN MEMORIATERULET NEM HASZNALHATO !!

// NEKUNK KELL TUDNUNK, HOGY HOGY HANY ELEMU TOMBOT FOGLALTUNK, ILLETVE, HOGY ADOTT TERULET LE VAN-E FOGLALVA
// LEHET NULLA MERETU TERULETET FOGLALNI, DE FEL IS KELL SZBADITANI
// SZABAD free (NULL) HIVAST CSINALNI 