// LANCOLT LISTAK - ADATSZERKEZET

// PROBLEMA - EGY TOMB MERETENEK NOVELESE, AMI DINAMIKUSAN FOLALT
// EGYES ELEMEK TAROLJAK AZ OKET KOVETO ELEM CIMET - MINDEN ELEM EGYESEVEL FOGLALHATO
// MINDEN ELEM ADATAT KIEGESZITJUK EGY MUTATOVAL, DE
//  - TETSZOLEGES MERETURE BOVITHETO DINAMIKUSAN
//  - UJ ELEM HOZZAADASANAK KOLTSEGE NAGYON KICSI
//  - ELEMEK TORLESE OLCSO MUVELET
//  ==> EGYES ELEMEK KULON JONNEK LETRE, ES KULON SZUNHETNEK MEG, NEM(!!) CSAK AZ OSSZES TAROLT ADAT ELETTARTAMAT FOGJUK KONTROLLALNI EGYSZERRE, HANEM AZ EGYES ELEMEKET KULON IS

// LANCBA VANNAK FUZVE A NODE-OK, MERT TAROLJAK A KOVETKEZO ELEM CIMET
// NYELVI SZINTEN EGY LANCOLT LISTABA FUZHETO ELEM EGY ONHIVATKOZO STRUKTURAVAL IRHATO LE
/*

    typedeg struct ListaElem {
        //  TETSZOLEGES ADATOK
        struct LisaElem *kov;
    } LisaElem;

*/
//  FONTOS  - AZ ONHIVATKOZAS CSAK MUTATO SEGITSEGEVEL OLDHATO MEG 
//          - EGY ADATTAG TIPUSA NEM EGYEZHET A STRUKTURAVAL AMIBEN SZEREPEL (VEGTELEN NAGY ADATSZERKEZET LENNE)
// ONHIVATKOZAS MIATT ITT A STRUKTURABAN NEM HAGYHATO EL A struct SZO

// LISTA NYILVANTARTASA

// LISTA ELSO ELEMENEK CIMET KELL ELTAROLNUNK, ETTOL ELINDULVA A TELJES ADATSZERKEZET BEJARHATO
// ELSO ELEMEK LISTAFEJNEK HIVJUK (HEAD, LIST HEAD) - ELTAROLJUK KULON
// TOBBI ELEM CIME KIOLVASHATO AZ EGYES LISTAELEMEKBOL
// LISTA = ELEMEK EGY MADZAGON
// UTOLSO ELEMBEN LEVO CIM = NULL - EZZEL JELEZZUK, HOGY NINCSEN TOVABBI ELEM A LISTABAN

// PL.:
//  ELSO ELEM CIME : eleje
//  MASODIK ELEM CIME : eleje->kov
//  ...
//  UTOLSO ELEM CIME : eleje->kov->kov->kov (AMI ITT NULL)
// eleje->kov UGYANAZ AZ MINT (*eleje).kov

// LISTA BEJARASA

//  CIKLUSSAL TUDUNK RAJTA VEGIGMENNI
/*

LisaElem *mozgo;
for (mozgo = eleje; mozgo != NULL; mozgo = mozgo->kov) {
    printf ("%d", mozgo->szam);
}
// elso ITT A LISTA ELEJE, A MEDDIG A NULL POINTERIG, A KOVEKETO AZ AKTUALIS ELEM ALTAL MUTATOTT 

*/

// LISTAMUVELETEK

//  POINTERMUVELETEKKEL ALLITJUK BE A LISTAK LANCOLASAT
//  (PAPIRON EGYSZERUBB TANULNI, OTT JOBBAN LATHATO A LANCOLAS)

// LISTAEPITES - BESZURAS ELORE I.

/*

ListaElem *uj;
//  uj ELEM DINAMIKUS LEFOGLALASA
uj = (ListaElem*) malloc (sizeof(ListaElem));
//  AZ uj ELEM KOVETKEZO POINTERENEK BEALLITASA AZ eleje ERTEKERE
uj->kov = eleje;
//  AZ ELEJE POINTER BEALLITASA AZ UJ ELEM CIMERE
eleje = uj;

*/

// LISTAEPITES - BESZURAS ELORE II. - ELOZO MUVELET MEGIRASA FGV-EKKEL

//  FGV VEGYE AT PARAMETERKENT A LISTA ELEJE MUTATOT ES A BESZURANDO ADATOT
//  MEGOLDHATO - FGV MINDIG VISSZAADJA AZ UJ "ELEJE " POINTERT, AMIVEL FELUL KELL IRNI A TAROLTAT
//  HASZNALATA : 
/*

ListaElem *eleje = NULL;
eleje = elore_beszur (eleje, 2);
// A BESZURO FGV, AMI VISSZAADJA AZ UJ "ELEJE" POINTERT
// UJ ELEMET HOZ LETRE, ES A LISTA ELEJERE FUZI
ListaElem *elore_beszur (ListaElem *eleje, int adat) {
    ListaElem *uj;
    uj = (ListaElem*) malloc(sizeof(ListaElem));
    uj->adat = adat;
    uj->koc = eleje;
    return uj;
}
// LISTA ELEJERE KERUL AZ UJ ELEM, EZRT PONT ANNAK A CIMEVEL TER VISSZA
// HA NEM TAROLJUK EL  AZ UJ CIMET, AKKOR AZ ELVESZ - EZERT A VISSZATERESI ERTEKET ELDOBNI, AZT NEM ELTAROLNI EGY VALTOZOBAN SULYOS HIBA!
*/

// LISTAEPITES - HOZZAFUZES I.

// HA ABBAN A SORRENDBEN SZERETNENK ELERNI AZ ELEMEKET, AMIBEN ERKEZTEK, AKKOR A LISTA VEGERE KELL BESZURNI OKET
/*

ListaElem *uj;
// LEFOGLALJUK AZ UJ ELEMET
uj = (ListaElem*) malloc (sizeof(ListaElem));
uj->adat = ...;

// MEGKERESSUK AZ UTOLSO ELEMET (MIVEL CSAK AZ ELSO POINTERE VAN MEG)
ListaElem *mozgo = eleje;
while (mozgo->kov != NULL) {
    mozgo = mozgo->kov;
}
// AZ UTOLSO ELEM "KOVETKEZO" POINTERET BEALLITJUK AZ UJ ELEM CIMERE, AZ UJ ELEMET PEDIG NULL-RA
mozgo->kov = uj;
uj->kov = NULL;

*/

// LISTAEPITES - HOZZAFUZES II.